#!/usr/bin/env node
/**
 * Typed asset generator: scans /assets/images and /assets/fonts and writes a typed index
 * (src/core/generated/assets.gen.ts). No more string paths / typos:
 *
 *   <Image source={Images.logo} />
 *   useFonts(Fonts)
 *
 * Usage:  npm run gen:assets          (write)
 *         npm run gen:assets -- --check  (CI: fail if the file is out of date)
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(root, 'src/core/generated/assets.gen.ts');

const IMAGE_EXT = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif']);
const FONT_EXT = new Set(['.ttf', '.otf']);

function walk(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const toCamel = (value) =>
  value
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^[A-Z]/, (c) => c.toLowerCase())
    .replace(/^(\d)/, '_$1');

function collect(folder, extensions, keyOf) {
  const base = join(root, 'assets', folder);
  const entries = new Map();
  for (const file of walk(base).sort()) {
    const ext = extname(file).toLowerCase();
    // RN picks @2x/@3x variants automatically - only reference the base file.
    if (!extensions.has(ext) || /@\dx\./.test(file)) continue;
    const key = keyOf(relative(base, file).slice(0, -ext.length));
    if (entries.has(key)) throw new Error(`Duplicate asset key "${key}" (${file})`);
    const importPath = relative(dirname(outFile), file).split(sep).join('/');
    entries.set(key, importPath);
  }
  return entries;
}

const images = collect('images', IMAGE_EXT, toCamel);
const fonts = collect('fonts', FONT_EXT, (name) => name.split(/[\\/]/).pop()); // key = font family name

const block = (name, entries, quoteKeys) => {
  const lines = [...entries].map(([key, path]) => `  ${quoteKeys ? `'${key}'` : key}: require('${path}'),\n`);
  return `export const ${name} = {${lines.length ? `\n${lines.join('')}` : ''}} as const;\n`;
};

const content = `/* eslint-disable */
// AUTO-GENERATED by scripts/gen-assets.mjs - do not edit. Run \`npm run gen:assets\`.

${block('Images', images, false)}
export type ImageName = keyof typeof Images;

${block('Fonts', fonts, true)}`;

if (process.argv.includes('--check')) {
  const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
  if (current !== content) {
    console.error('assets.gen.ts is out of date. Run `npm run gen:assets`.');
    process.exit(1);
  }
  console.log('assets.gen.ts is up to date.');
} else {
  writeFileSync(outFile, content);
  console.log(`Generated ${relative(root, outFile)} (${images.size} images, ${fonts.size} fonts)`);
}
